### ISSUE TITLE
webpay rest api not work

### ISSUE THREAD

**Issue by sagar364490** [TransbankDevelopers/transbank-plugin-magento2-webpay-rest#41]
u\i have install magento 2 in webpay rest api but not work 
![image](https://user-images.githubusercontent.com/106227124/170937031-9f7d8ab1-3dec-4ac5-bb13-9a0488d7af0e.png)

**Comment by isabellaahc** [comment]
Hi @sagar364490, please follow the instructions to report an issue.
We need more information to replicate this issue:
- Magento version
- PHP version
- Transbank plugin version

**Comment by ludcl** [comment]
It's probably late for a response, but probably the access to the integration environment is not enabled from your country.

If we visit that URL from Chile (_https://webpay3gint.transbank.cl/webpayserver/initTransaction_), we are redirected to this URL: _https://webpay3gint.transbank.cl/webpayserver/init_transaction.cgi_

It has nothing to do with the integration in Magento because you should be able to navigate directly to that URL from your browser and the error you are getting is that you are unable to reach the server.

You can try a VPN.
